"""empty message

Revision ID: 2a575364885f
Revises: 04ba6ac043c5
Create Date: 2024-07-05 10:27:34.845778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a575364885f'
down_revision = '04ba6ac043c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('user_favourites_saved_characters_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_favourites_saved_vehicles_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_favourites_saved_planets_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['character_id'])
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['planet_id'])
        batch_op.drop_column('saved_vehicles')
        batch_op.drop_column('saved_planets')
        batch_op.drop_column('saved_characters')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_characters', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('saved_planets', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('saved_vehicles', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_favourites_saved_planets_fkey', 'planets', ['saved_planets'], ['planet_id'])
        batch_op.create_foreign_key('user_favourites_saved_vehicles_fkey', 'vehicles', ['saved_vehicles'], ['vehicle_id'])
        batch_op.create_foreign_key('user_favourites_saved_characters_fkey', 'characters', ['saved_characters'], ['character_id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('planet_id')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###
