"""empty message

Revision ID: ccb8bdaae573
Revises: 2a575364885f
Create Date: 2024-07-06 15:15:55.814936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb8bdaae573'
down_revision = '2a575364885f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_planeta', sa.Integer(), nullable=True))
        batch_op.drop_constraint('user_favourites_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['id_planeta'], ['planet_id'])
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_favourites_planet_id_fkey', 'planets', ['planet_id'], ['planet_id'])
        batch_op.drop_column('id_planeta')

    # ### end Alembic commands ###
